# Generated by Django 5.2.8 on 2025-11-11 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', help_text='Project status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the project was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the project was last updated')),
                ('owner', models.ForeignKey(help_text='The user who owns the project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(help_text='Users who are participants in the project', related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
