# Generated by Django 5.1.4 on 2025-03-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', help_text='Project status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the project was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the project was last updated')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
