# Generated by Django 5.1.4 on 2025-03-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('in_progress_tasks', models.PositiveIntegerField(default=0)),
                ('pending_tasks', models.PositiveIntegerField(default=0)),
                ('average_completion_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project Analytics',
                'verbose_name_plural': 'Projects Analytics',
            },
        ),
    ]
